---
- hosts: localhost
  become: true
  vars:
    create_containers: 1
    default_container_name: redis
    default_container_image: redis
          
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Pull default docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull
    - name: Create container
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        state: started
        ports: "6379:6379"
      with_sequence: count={{ create_containers }}
